<?php $this->headTitle($this->title) ?>
<div class="navbar">
    <a class="btn btn-success" href="<?php echo $this->url(array('controller'=>'user', 'action'=>'add'));?>">
        Novo usuário
    </a>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        Lista de usuários        
    </div>
    <div class="panel-body">
    <?php echo $this->partial('itemsCountPerPage.phtml', array('form' => $this->form)) ?>
    </div>
    <table class="table table-hover">
        <tr>
            <th>Usuário</th>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Grupo</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach($this->users as $user) : ?>
        <tr>
            <td>
                <a href="<?php echo $this->url(array('action' => 'view','id' => $user->getId())) ?>">
                <?php echo $this->escape($user->getUsername()) ?>
                </a>
            </td>
            <td><?php echo $this->escape($user->getName()) ?></td>
            <td><?php echo $this->escape($user->getEmail()) ?></td>
            <td><span class="label label-success"><?php echo $this->escape($user->getRuleFormatted()) ?></span></td>
            <td>
                <a class="btn btn-default btn-xs" href="<?php echo $this->url(array('action' => 'edit','id' => $user->getId())) ?>">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a class="btn btn-default btn-xs" href="<?php echo $this->url(array('action' => 'delete','id' => $user->getId())) ?>">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
    <div class="panel-footer">
    <?php echo $this->users->getAdapter()->count() ?> registros encontrados
    </div>
</div>
<?php echo $this->paginationControl($this->users, 'Sliding', 'paginator.phtml') ?>
