<div class="container">
	<div class="sm-12">
		<div class="panel panel-default">
			<div class="panel-heading"><h1>Sobre o Projeto</h1></div>
			<div class="panel-body">
				<p class="well">
					Este projeto inicialmente foi proposto pelos professores do UniCesumar
					como sendo uma ferramenta diferente para propor e conhecer os interesses 
					dos alunos.
				</p>
				
				<p>
					O professor Vander fez uma proposta ainda mais ousada de desenvolver o 
					primeiro <strong>Chá com Conhecimento</strong> para fazer algo mais interessante ainda.
				</p>
				
				<p>
					Inspirado na ideia do fishbow, o professor Eduardo Bona e os alunos do 
					3o ano do curso de Sistemas para Internet colocaram este sistema em sua 
					primeira versão para rodar em 3 semanas.
				</p>
				
				<p>
					Todo o projeto está disponível no Github e pode ser usado e também 
					receber contribuições de todos os interessados.
				</p>
				
				<p>
					Tem sugestões, elogios e críticas? Entre no Github do projeto e mande sua opinião.
				</p>
				
				<p>
					<a href="http://github.com/eduardobona/fishbow" class="btn btn-success btn-lg" role="button">Ir para o projeto no Github</a>
				</p>
			</div>
		</div>
	</div>
</div>