<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span class="glyphicon glyphicon-lock"></span> Login
                </h3>
            </div>
            <div class="panel-body">
                <?php echo $this->flashMessages(); ?>
                <?php echo $this->form->renderForm(false) ?>
                <fieldset>
                    <div class="form-group">
                    <?php echo $this->form->ra ?>
                    </div>
                    <div class="form-group">
                    <?php echo $this->form->password ?>
                    </div>
                    <?php echo $this->form->submit ?>
                </fieldset>
            </div>
        </div>
    </div>
</div>
