<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span class="glyphicon glyphicon-lock"></span> Login
                </h3>
            </div>
            <div class="panel-body">
                <?php echo $this->flashMessages(); ?>
                <?php echo $this->form->renderForm(false) ?>
                <fieldset>
                    <div class="form-group">
                    <label>Email</label>
                    <?php echo $this->form->email ?>
                    </div>
                    <div class="form-group">
                    <label>Senha: (seu RA)</label>
                    <?php echo $this->form->senha ?>
					<p class="help-block"><small>Caso seu RA comece com dígitos 0, ignore-os.</small></p>
					<p class="help-block"><small>Para: 00928382-90, Digite: 92838290</small></p>
                    </div>
                    <?php echo $this->form->submit ?>
                </fieldset>
            </div>
        </div>
    </div>
</div>
