<?php echo $this->doctype() ?>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <?php $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?php $this->headTitle()->setSeparator(' - '); ?>
    <?php $this->headTitle('CMS'); ?>
    <!-- Core CSS - Include with every page -->
    <?php $this->headLink()->appendStylesheet('/assets/admin/css/bootstrap.min.css') ?>
    <?php $this->headLink()->appendStylesheet('/assets/admin/font-awesome/css/font-awesome.css') ?>

    <!-- SB Admin CSS - Include with every page -->
    <?php $this->headLink()->appendStylesheet('/assets/admin/css/sb-admin.css') ?>
  
    <!-- Core Scripts - Include with every page -->
    <?php $this->headScript()->appendFile('/assets/admin/js/jquery-1.10.2.js') ?>
    <?php $this->headScript()->appendFile('/assets/admin/js/bootstrap.min.js') ?>
    <?php $this->headScript()->appendFile('/assets/admin/js/plugins/metisMenu/jquery.metisMenu.js') ?>
  
    <!-- SB Admin Scripts - Include with every page -->
    <?php $this->headScript()->appendFile('/assets/admin/js/sb-admin.js') ?>
    
    <?php $this->navigation($this->container()) ?>
    
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url(array('module' => 'admin', 'controller'=>'index'), 'default', true) ?>">Painel</a>
            </div>
            <!-- /.navbar-header -->
        
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="<?php echo $this->url(array('controller'=>'login', 'action'=>'logout'));?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
        
            <div class="navbar-default navbar-static-side" role="navigation">
                <div class="sidebar-collapse">
                <?php echo $this->navigation()->menu()->setPartial(array('menu.phtml','admin'))->render() ?>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <?php echo $this->partial('pageheader.phtml', 'admin') ?>
                    <?php echo $this->flashMessages(); ?>
                    <?php echo $this->navigation()->breadcrumbs()->setPartial(array('breadcrumbs.phtml', 'admin'))->render() ?>
                    <?php echo $this->layout()->content ?>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->headScript() ?>
</body>
</html>