<?php echo $this->doctype() ?>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <?php $this->headTitle()->setSeparator(' - ') ?>
    <?php $this->headTitle('Chá com conhecimento') ?>
    <?php $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?> 
    <?php $this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Dosis:300,400,500,600,700') ?>
    <?php $this->headLink()->appendStylesheet('/assets/default/css/bootstrap.min.css') ?>
    <?php $this->headLink()->appendStylesheet('/lib/css/bootstrap.min.css') ?>
    <?php $this->headScript()->prependFile('/assets/default/js/bootstrap.min.js') ?>
    <?php $this->headLink()->appendStylesheet('https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css') ?>
    <?php $this->headScript()->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js') ?>
    
    <?php $this->headLink()->appendStylesheet('/assets/default/css/main.css') ?>
    
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    
    
</head>
<body>
	<div class="container-fluid">
	
		<div class="row">
			<div id="carousel" class="carousel slide" data-ride="carousel">
				<div class="carousel-inner">
					<div class="item active">
						<a href="/"><img src="/assets/default/images/novo_banner.jpg" alt="Chá com Conhecimento"></a>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-sm-12" style="padding: 20px 0px">
			<div class="col-sm-12 text-center">
				<a href="/index" class="  btn btn-lg btn-success" role="button">Temas e Assuntos</a>
				<a href="/index/sobre" class="  btn btn-lg btn-success" role="button">Sobre o Projeto</a>
				<a href="http://github.com/eduardobona/fishbow" class="btn btn-success btn-lg" role="button">Baixe o Projeto</a>
			</div>
		</div>
		
		<div class="row temas">
			<div class="col-md-12">
				<div class="row">
					<div class="col-sm-12">					
						<?php echo $this->flashMessages(); ?>
					</div>

<?php echo $this->layout()->content ?>

				</div>
			</div>
		</div>
	</div>

	<div class="modal fade modal-login" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Chá com Conhecimento</h4>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-sm-6">
							<div class="row">
								<label class="col-sm-12"><h2>Quero me cadastrar</h2></label>
								<div class="form-group col-sm-12">
									<label>Nome</label>
									<input type="text" class="form-control">            
								</div>
								<div class="form-group col-sm-12">
									<label>Email</label>
									<input type="text" class="form-control">            
								</div>
								<div class="form-group col-sm-12">
									<label>Senha</label>
									<input type="password" class="form-control">            
								</div>
								<div class="form-group col-sm-12">
									<button type="submit" class="btn btn-primary col-sm-6 pull-right">Cadastrar</button>
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<label class="col-sm-12"><h2>Já sou cadastrado</h2></label>
								<div class="form-group col-sm-12">
									<label>Email</label>
									<input type="text" class="form-control">            
								</div>
								<div class="form-group col-sm-12">
									<label>Senha</label>
									<input type="password" class="form-control">            
								</div>
								<div class="form-group col-sm-12">
									<button type="submit" class="btn btn-success col-sm-6 pull-right">Entrar</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	 
	<?php echo $this->headScript() ?>
</body>
</html>
