<?php echo $this->doctype() ?>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <?php $this->headTitle()->setSeparator(' - ') ?>
    <?php $this->headTitle('Website') ?>
    <?php $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?> 
    <?php $this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Dosis:300,400,500,600,700') ?>
    <?php $this->headLink()->appendStylesheet('/assets/default/css/bootstrap.min.css') ?>
    <?php $this->headLink()->appendStylesheet('/lib/css/bootstrap.min.css') ?>
    <?php $this->headScript()->prependFile('/assets/default/js/bootstrap.min.js') ?>
    <?php $this->headLink()->appendStylesheet('https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css') ?>
    <?php $this->headScript()->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js') ?>
    
    <?php $this->headLink()->appendStylesheet('/assets/default/css/main.css') ?>
    
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    
    
</head>

	<header>
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12 center">
					<img src="/assets/default/images/cha.png">
					<h2>Sugira temas ou assuntos e vote neles!</h2>
					<h2>Os mais votados serão discutidos em eventos e palestras!</h2>
					<button class="btn btn-success btn-lg center-block" data-toggle="modal" data-target=".modal-tema">Cadastre um novo tema</button>
				</div>
			</div>
		</div>
		
	</header>
	<section class="top4">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-5 col-md-offset-1">
					<div class="panel panel-default">
					  <div class="panel-heading">
					  	<h3>Tema Sugerido</h3>
					  </div>
					  <div class="panel-body">
					   
					    <p>Relógio da Microsoft será compatível com Android e iOS</p>
					    
					  </div>
					  <div class="panel-footer">
					  	<div class="progress progress-striped active">
					  	  <div class="progress-bar"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
					  	    <span class="sr-only">45% Complete</span>
					  	  </div>
					  	</div>
					  </div>
					</div>			
				</div>
			</div>
		</div>		
	</section>
	<div class="container-fluid">

		<main>
			<div class="row temas">
				<div class="col-md-12">
					<div class="row">

						<div class="col-sm-12">					
							<?php echo $this->flashMessages(); ?>
						</div>

<?php echo $this->layout()->content ?>

					</div>
				</div>
			</div>
		</main>

	</div>		

	<div class="modal fade modal-login" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Chá com Conteúdo</h4>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-sm-6">
							<div class="row">
								<label class="col-sm-12"><h2>Quero me cadastrar</h2></label>
								<div class="form-group col-sm-12">
									<label>Nome</label>
									<input type="text" class="form-control">            
								</div>
								<div class="form-group col-sm-12">
									<label>Email</label>
									<input type="text" class="form-control">            
								</div>
								<div class="form-group col-sm-12">
									<label>Senha</label>
									<input type="password" class="form-control">            
								</div>
								<div class="form-group col-sm-12">
									<button type="submit" class="btn btn-primary col-sm-6 pull-right">Cadastrar</button>
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="row">
								<label class="col-sm-12"><h2>Já sou cadastrado</h2></label>
								<div class="form-group col-sm-12">
									<label>Email</label>
									<input type="text" class="form-control">            
								</div>
								<div class="form-group col-sm-12">
									<label>Senha</label>
									<input type="password" class="form-control">            
								</div>
								<div class="form-group col-sm-12">
									<button type="submit" class="btn btn-success col-sm-6 pull-right">Entrar</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal fade modal-tema" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">

		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Fishbow</h4>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-sm-12">

							<div class="form-group col-sm-12">
								<label><h2>Cadastre um novo Tema</h2></label>
								<label>Você gosta de tecnologia, e está sempre antenado nas últimas novidades? Que tal discutirmos alguns assuntos de seu interesse?</label>
								<label>Cadastre um tema para discutirmos!</label>
							</div>
							<div class="form-group col-sm-12">
								<textarea class="form-control"></textarea>            
							</div>
							<div class="form-group col-sm-12">
								<button type="submit" class="btn btn-primary pull-right col-sm-3">Cadastrar</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal fade modal-assunto" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">

		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Chá com Conteúdo</h4>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-sm-12">

							<div class="form-group col-sm-12">
								<label><h2>Cadastre um novo Assunto:</h2></label>
								<label>Este tema é do seu interesse?</label>
								<label>Cadastre um assunto relacionado para discutirmos!</label>
							</div>
							<div class="form-group col-sm-12">
								<textarea class="form-control"></textarea>            
							</div>
							<div class="form-group col-sm-12">
								<button type="submit" class="btn btn-primary pull-right col-sm-3">Cadastrar</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	


	<?php echo $this->headScript() ?>
</body>
</html>
