
	<!-- assunto -->
	<div class="modal fade modal-assunto-<?= $this->tema->getIdTema() ?>" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Sugira um assunto</h4>
				</div>
				<div class="modal-body">
					<form action="/assunto/index/id/<?= $this->tema->getIdTema() ?>" method="post">
						<div class="row">
							<div class="col-sm-12">
								<div class="form-group col-sm-12">
									<label>Cadastre um assunto relacionado para discutirmos!</label>
								</div>
								<div class="form-group col-sm-12">
									<input id="assunto" name="assunto" type="text" class="form-control" placeholder="Insira o assunto desejado.." required />
								</div>
								<div class="form-group col-sm-12">
									<button type="submit" class="btn btn-primary pull-right col-sm-3">Cadastrar</button>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- assunto -->